In [1]:
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, stringr, readxl, data.table, gdata, purrr)
source("functions.R")

Loading required package: pacman

In [4]:
years <- 2010:2015
file_paths <- paste0("../data/output/data-", years, ".csv")

final_ma_data <- file_paths %>%
  map_dfr(~read_csv(.x, col_types = cols(.default = "c"))) %>%
  type_convert()

glimpse(final_ma_data)

write_csv(full_ma_data, "../data/output/final-ma-data.csv")

── Column specification ────────────────────────────────────────────────────────
cols(
  .default = col_double(),
  contractid = col_character(),
  state = col_character(),
  county = col_character(),
  org_type = col_character(),
  plan_type = col_character(),
  partd = col_character(),
  snp = col_character(),
  eghp = col_character(),
  org_name = col_character(),
  org_marketing_name = col_character(),
  plan_name = col_character(),
  parent_org = col_character(),
  contract_date = col_character(),
  state_long = col_character(),
  county_long = col_character(),
  org_parent = col_character()
)
ℹ Use `spec()` for the full column specifications.

Rows: 440,877
Columns: 110
$ contractid          <chr> "H0084", "H0084", "H0084", "H0084", "H0084", "H008…
$ planid              <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ fips                <dbl> 48029, 48037, 48039, 48047, 48067, 48071, 48085, 4…
$ n_nonmiss           <dbl> 11, 11, 12, 0, 9, 0, 11, 0, 12, 10, 7, 0, 5, 11, 1…
$ avg_enrollment      <dbl> 38.90909, 19.72727, 26.83333, NA, 16.11111, NA, 15…
$ sd_enrollment       <dbl> 13.946000, 2.195036, 4.152400, NA, 1.452966, NA, 2…
$ min_enrollment      <dbl> 19, 17, 20, NA, 14, NA, 13, NA, 39, 13, 14, NA, 13…
$ max_enrollment      <dbl> 61, 23, 33, NA, 19, NA, 19, NA, 102, 38, 19, NA, 1…
$ first_enrollment    <dbl> 19, 18, 20, NA, 14, NA, 13, NA, 39, 13, 14, NA, 13…
$ last_enrollment     <dbl> 61, 23, 31, NA, 19, NA, 19, NA, 102, 37, 19, NA, 1…
$ state               <chr> "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "T…
$ county              <chr> "Bexar", "Bowie", "Brazoria", "Brooks", "Cass", "C…
$ org_type            <chr> "Local CCP", "Local CCP", "Local CCP", "Local CCP"…
$ plan_type           <chr> "Local PPO", "Local PPO", "Local PPO", "Local PPO"…
$ partd               <chr> "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "…
$ snp                 <chr> "No", "No", "No", "No", "No", "No", "No", "No", "N…
$ eghp                <chr> "No", "No", "No", "No", "No", "No", "No", "No", "N…
$ org_name            <chr> "CARE IMPROVEMENT PLUS OF TEXAS INSURANCE COMPANY"…
$ org_marketing_name  <chr> "Care Improvement Plus", "Care Improvement Plus", …
$ plan_name           <chr> "Care Improvement Plus Medicare Advantage (PPO)", …
$ parent_org          <chr> "XLHealth Corporation", "XLHealth Corporation", "X…
$ contract_date       <chr> "1/1/2009 0:00:00", "1/1/2009 0:00:00", "1/1/2009 …
$ state_long          <chr> "texas", "texas", "texas", "texas", "texas", "texa…
$ county_long         <chr> "Bexar", "Bowie", "Brazoria", "Brooks", "Cass", "C…
$ n_elig              <dbl> 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12…
$ n_enrol             <dbl> 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12…
$ avg_eligibles       <dbl> 211132.00000, 16173.25000, 33784.41667, 1519.08333…
$ sd_eligibles        <dbl> 1871.474431, 77.170561, 383.282108, 10.237705, 46.…
$ min_eligibles       <dbl> 208483, 16037, 33281, 1501, 6752, 3077, 62588, 417…
$ max_eligibles       <dbl> 213944, 16300, 34335, 1532, 6887, 3946, 67435, 424…
$ first_eligibles     <dbl> 208936, 16107, 33333, 1504, 6807, 3932, 62588, 422…
$ last_eligibles      <dbl> 213944, 16230, 34335, 1525, 6887, 3096, 67435, 423…
$ avg_enrolled        <dbl> 70644.16667, 1826.00000, 5642.16667, 256.75000, 83…
$ sd_enrolled         <dbl> 1459.0172180, 65.2031790, 141.8423154, 10.1634371,…
$ min_enrolled        <dbl> 67550, 1668, 5286, 232, 742, 589, 10371, 12, 46868…
$ max_enrolled        <dbl> 72408, 1880, 5753, 264, 858, 720, 11755, 16, 49888…
$ first_enrolled      <dbl> 67550, 1668, 5286, 232, 742, 589, 10371, 12, 46868…
$ last_enrolled       <dbl> 72408, 1863, 5725, 263, 858, 720, 11755, 15, 49822…
$ ssa                 <dbl> 45130, 45170, 45180, 45210, 45260, 45280, 45310, 4…
$ ncount              <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ breastcancer_screen <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ rectalcancer_screen <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ cv_diab_cholscreen  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ glaucoma_test       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ monitoring          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ flu_vaccine         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ pn_vaccine          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ physical_health     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ mental_health       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ osteo_test          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ physical_monitor    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ primaryaccess       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ osteo_manage        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ diab_healthy        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ bloodpressure       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ ra_manage           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ copd_test           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ bladder             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ falling             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ nodelays            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ doctor_communicate  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ carequickly         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ customer_service    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ overallrating_care  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ overallrating_plan  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ complaints_plan     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ appeals_timely      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ appeals_review      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ leave_plan          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ audit_problems      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ hold_times          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ info_accuracy       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ ttyt_available      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ new_contract        <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ partc_score         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ partcd_score        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ Star_Rating         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ aged_parta          <dbl> 460.24, 465.50, 491.30, 431.59, 431.84, 594.03, 49…
$ aged_partb          <dbl> 398.74, 403.29, 425.64, 373.91, 374.14, 514.64, 43…
$ risk_ab             <dbl> 953.76, 895.64, 941.69, 1073.64, 942.86, 1271.06, …
$ risk_star5          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_star45         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_star4          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_star35         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_star3          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_star25         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_bonus5         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_bonus35        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ risk_bonus0         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ year                <dbl> 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 20…
$ ma_rate             <dbl> 953.76, 895.64, 941.69, 1073.64, 942.86, 1271.06, …
$ cv_cholscreen       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ diab_cholscreen     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ diabetes_eye        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ diabetes_kidney     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ diabetes_bloodsugar <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ diabetes_chol       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ corrective_action   <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ low_score           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ org_parent          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ bmi_assess          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ older_medication    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ older_function      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ older_pain          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ readmissions        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ access_problems     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ coordination        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ improve             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ enroll_timely       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ specialneeds_manage <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…

  year non_na_stars
1 2010 60519
2 2011 55249
3 2012 58169
4 2013 64174
5 2014 58636
6 2015 60819

   contractid year Star_Rating risk_bonus5 ma_rate
1  H0022      2015 NA          822.37      812.29
2  H0022      2015 NA          802.42      796.33
3  H0022      2015 NA          772.59      762.29
4  H0022      2015 NA          778.71      768.33
5  H0022      2015 NA          777.67      766.94
6  H0022      2015 NA          798.97      777.18
7  H0022      2015 NA          788.36      777.10
8  H0022      2015 NA          802.90      781.59
9  H0022      2015 NA          815.16      807.52
10 H0022      2015 NA          800.05      778.23